# Generated by Django 4.0.6 on 2022-08-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='action',
            field=models.CharField(choices=[('subscribe', 'subscribed to'), ('post', 'shared a '), ('avatar', 'changed avatar')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
