# Generated by Django 4.0.5 on 2022-07-10 18:57

from django.db import migrations
import djangogramm.models
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=thumbnails.fields.ImageField(blank=True, upload_to=djangogramm.models.rename_media),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=thumbnails.fields.ImageField(blank=True, upload_to=djangogramm.models.rename_avatar),
        ),
    ]
