# Generated by Django 4.0.5 on 2022-07-10 19:44

from django.db import migrations
import djangogramm.models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0004_alter_image_image_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=djangogramm.models.rename_media),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=djangogramm.models.rename_avatar),
        ),
    ]
