# Generated by Django 4.0.5 on 2022-07-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0005_alter_image_image_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='validation_key',
            field=models.CharField(default='Gw2LHVlk5N5Znk51oRaL', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
