# Generated by Django 4.0.5 on 2022-07-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0006_user_validation_key_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='validation_key',
            field=models.CharField(default='Zr39h4mZwD4xgr0soxMC', max_length=20),
        ),
    ]
