# Generated by Django 4.0.5 on 2022-07-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0007_alter_user_validation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='validation_key',
            field=models.CharField(default='6FbrbSbLvPQrziDbdAP9', max_length=20),
        ),
    ]
