# Generated by Django 4.0.5 on 2022-07-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0008_alter_user_validation_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='validation_key',
        ),
    ]
