# Generated by Django 4.0.5 on 2022-07-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0011_remove_user_following_followings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followings',
            new_name='Following',
        ),
    ]
