# Generated by Django 4.0.5 on 2022-07-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0013_following_time_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_text',
            new_name='action',
        ),
        migrations.AddField(
            model_name='news',
            name='followed_user',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
