# Generated by Django 4.0.5 on 2022-07-18 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0014_rename_news_text_news_action_news_followed_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='followed_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_followed_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
