# Generated by Django 4.0.5 on 2022-07-18 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0015_alter_news_followed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangogramm.post'),
        ),
    ]
